[package]
name = "cashcontracts"
version = "0.1.3"
authors = ["tobiasruck <ruck.tobias@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
hex = "0.3.2"
num = "0.2.0"
num-derive = "0.2.4"
num-traits = "0.2.6"
ripemd160 = "0.8.0"
sha2 = "0.8.0"
